name: SMOTE_ENC
channels:
  - conda-forge
dependencies:
  - python=3.6.8
  - numpy=1.16.2
  - pandas=0.24.2
  - pip=20.3.3
  - scikit-learn=0.20.3
  - matplotlib
  - scipy=1.2.1
  - seaborn
  - imbalanced-learn=0.4.3
    